### ISSUE TITLE
Dimension mismatch 

### ISSUE THREAD

**Issue by finnick99** [dlam4h/OCD-PyTorch#5]
when i use the first code,change batch_size parameter，and appear this error
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [64, 3, 3, 3], but got 5-dimensional input of size [74, 8, 3, 224, 224] instead
how to solve this and why appear this ,Please help me, i'm a beginner，plz，Looking forward to your reply

**Comment by dlam4h** [comment]
> 8

**Comment by dlam4h** [comment]
@finnick99 can I see your code?

**Comment by finnick99** [comment]
i use your first code ,code1-code for paper,i only modify batch_size，74，but runtimeerror ,i dont kown why

**Comment by finnick99** [comment]
Traceback (most recent call last):
  File "train.py", line 110, in <module>
    train()
  File "train.py", line 86, in train
    outputs = model(data)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/drive/My Drive/papercode/model.py", line 88, in forward
    x = self.features(x)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/conv.py", line 396, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [64, 3, 3, 3], but got 5-dimensional input of size [74, 8, 3, 224, 224] instead

**Comment by dlam4h** [comment]
@finnick99 Maybe you use "train_dataloader = DataLoader(train_data,batch_size = 74, shuffle = True, num_workers = 0)" to change Batchsize. This code use a fixed Batchsize. So, if you want to change Batchsize, you should modify dataset_OCD.py.

**Comment by finnick99** [comment]
But I did not find the batch_size  parameter in dataset_OCD.py, which one should be modified, can you tell me, sorry for the trouble

**Comment by dlam4h** [comment]
@finnick99  when you use batch_size = 74, the size of input tensor is [74, 8, 3, 224 ,224], you can reshape to [74 * 8, 3, 224, 224], and the real batch_size will be 592. Line 74 in train.py

**Comment by finnick99** [comment]
I modified this in dataset_OCD.pya
imgs = np.zeros((50*8,3,self.r_size,self.c_size))
masks = np.zeros((50*8,self.r_size,self.c_size))

and this in train.py
train_dataloader = DataLoader(train_data,batch_size = 400, shuffle = True, num_workers = 0)

do you mean this？
